// ===== Anagram Quest — static game data =====
// Kept separate from anagram-quest.js so the word lists/weights can be
// tuned without touching game logic.
(function () {
  // Round 5 bonus rack always comes from one of these — every entry is a
  // genuine, reasonably common 9-letter English word, and deliberately
  // singular/base-form (an adjective, an uncountable noun, or a verb-form
  // noun that doesn't pluralize) — NEVER a plain plural (no "HOSPITALS",
  // "CAMPFIRES", etc. — those live in BONUS_WORDS_PLURAL below instead,
  // drawn from much more rarely). No country or city names either —
  // pickBonusWord() below never draws from a name list, only genuine
  // dictionary words. Every single entry here was verified two ways before
  // being added: (1) present, case-insensitively, in data/dictionary.txt —
  // the same file isValidAnagramQuestWord() checks a player's submission
  // against, so Round 5's own answer is always guaranteed accepted — and
  // (2) not present in geo-data.js's COUNTRIES/CITIES lists. Deliberately
  // large (600+) so two games landing on the same word is rare rather than
  // the norm. Grouped by rough theme purely for readability — no code
  // anywhere treats these as separate groups, it's one flat pool.
  const BONUS_WORDS = [
    // starter set
    'ADVENTURE','BUTTERFLY','DANGEROUS','BEAUTIFUL','TELEPHONE','NEWSPAPER',
    'CHOCOLATE','DISCOVERY','ASTRONAUT','SPACESHIP','METEORITE','UNIVERSAL',
    'FURNITURE','KNOWLEDGE','EDUCATION','FANTASTIC','GENERATOR','HAPPINESS',
    'BOUNTIFUL','LIGHTNING','MAGNITUDE','QUIETNESS','SATELLITE','TELESCOPE',
    'UNDERWEAR','WATERFALL','EXCELLENT','YESTERDAY','ZOOLOGIST','GRASSLAND',
    'HAMBURGER','JELLYFISH','MOONLIGHT','NIGHTMARE','OVERBOARD','SNOWSTORM',
    'VEGETABLE','YOUNGSTER','BUTTERCUP','GEOGRAPHY','HURRICANE','SUBMARINE',
    'AVALANCHE','CROCODILE','HARMONICA','DEMOCRACY','CARNATION','PARACHUTE',
    'SANDPAPER','GRAVEYARD','FOOTPRINT','SNOWFLAKE','PINEAPPLE','WONDERFUL',
    'BLACKBIRD','MAGNETISM','CONTINENT',
    // animals, nature & the outdoors
    'ALBATROSS','ALLIGATOR','ARMADILLO','ARTILLERY','ASPARAGUS','BLUEBERRY',
    'DRAGONFLY','DRIFTWOOD','EARTHWORM','EVERGREEN','FROSTBITE','GREENWOOD',
    'HAILSTORM','MAYFLOWER','MOONSHINE','PORCUPINE','RASPBERRY','ROUNDWORM',
    'SANDSTORM','SHELLFISH','SPIDERWEB','SUNFLOWER','SURFBOARD','SWORDFISH',
    'TARANTULA','WHIRLWIND','CENTIPEDE','CHAMELEON','CHRYSALIS','MILLIPEDE',
    'BLUEGRASS','CRABGRASS','CRANBERRY','RAINSTORM','LANDSLIDE','ECOSYSTEM',
    'RENEWABLE','RECYCLING','POLLUTION',
    // food & drink
    'SPAGHETTI','CASSEROLE','CORNBREAD','CROISSANT','ENCHILADA','FRUITCAKE',
    'GUACAMOLE','JELLYBEAN','BUBBLEGUM','BREAKFAST','CHAMOMILE','CHAMPAGNE',
    'CORIANDER','SPEARMINT','SEASONING',
    // house & household objects
    'BOOKSHELF','BOOKSTORE','FIREPLACE','FLOWERPOT','FOOTSTOOL','LIGHTBULB',
    'STAIRCASE','WALLPAPER','MOUTHWASH','HAIRBRUSH','DEODORANT','COSMETICS',
    'PORCELAIN','GLASSWARE','COFFEEPOT','MICROWAVE','CAMCORDER','PROJECTOR',
    'HEADPHONE','BASEBOARD','BILLBOARD','CARDBOARD','CLIPBOARD','DASHBOARD',
    'HEADBOARD','SIDEBOARD','SIGNBOARD','SNOWBOARD','WASHBOARD','BATHHOUSE',
    'BIRDHOUSE','BOATHOUSE','CLUBHOUSE','FARMHOUSE','FIREHOUSE','GATEHOUSE',
    'JAILHOUSE','PENTHOUSE','PLAYHOUSE','ROADHOUSE','TOWNHOUSE','WAREHOUSE',
    'WORKHOUSE','DOLLHOUSE','BRIMSTONE','PLENTIFUL','FLAGSTONE','GALLSTONE',
    'HEADSTONE','LIMESTONE','MILESTONE','MILLSTONE','MOONSTONE','SANDSTONE',
    'TOMBSTONE','BRICKWORK','BRUSHWORK','CLOCKWORK','FRAMEWORK','FIELDWORK',
    'GUESSWORK','HANDIWORK','HOUSEWORK','PAPERWORK','PATCHWORK','STONEWORK',
    'HEADLIGHT','HIGHLIGHT','LAMPLIGHT','LIMELIGHT','SPOTLIGHT','STARLIGHT',
    'STOPLIGHT','FIRELIGHT','TREADMILL','COURTYARD','STOCKYARD','RIVERSIDE',
    'BROADSIDE','UNDERSIDE','COURTSIDE','HEARTLAND','MARSHLAND','WASTELAND',
    'FAIRYLAND','DREAMLAND','CLASSROOM','COURTROOM','BOARDROOM','STOREROOM',
    'STOCKROOM','CLOAKROOM','GUIDEBOOK','SCRAPBOOK','STORYBOOK','CHECKBOOK',
    'TIMETABLE','TURNTABLE','SCARECROW',
    // people & professions
    'ARCHITECT','CARPENTER','SCIENTIST','BIOLOGIST','PHYSICIST','LIBRARIAN',
    'PUBLISHER','NAVIGATOR','CONDUCTOR','GUITARIST','VIOLINIST','TRUMPETER',
    'FISHERMAN','SWORDSMAN','GLADIATOR','POLICEMAN','PRESIDENT','SPECTATOR',
    'ATHLETICS','BATTALION','COMMANDER','PRINCIPAL','QUEENSHIP','OWNERSHIP',
    'COURTSHIP','STEAMSHIP','CHILDHOOD','ADULTHOOD','FALSEHOOD','STATEHOOD',
    'WOMANHOOD',
    // body & health
    'ANKLEBONE','CHEEKBONE','FINGERTIP','HEARTBEAT','CARTILAGE','DIGESTION',
    'NUTRITION','ENDURANCE','INTESTINE','CAPILLARY','GYMNASIUM',
    // science, space & technology
    'CHEMISTRY','BAROMETER','PEDOMETER','PARAMETER','VOLTMETER','ALTIMETER',
    'PERIMETER','PERISCOPE','HOROSCOPE','GYROSCOPE','MEGAPHONE','SAXOPHONE',
    'XYLOPHONE','HOMOPHONE','AEROPLANE','MONOPLANE','POTASSIUM','MAGNESIUM',
    'PLUTONIUM','CIRCUITRY','ANTHOLOGY','ASTROLOGY','ETYMOLOGY','GENEALOGY',
    'MYTHOLOGY','PATHOLOGY','NEUROLOGY','SOCIOLOGY','RADIOLOGY','PHONOLOGY',
    'BIOGRAPHY',
    // vehicles & places
    'HOUSEBOAT','MOTORBOAT','SPEEDBOAT','STEAMBOAT','FERRYBOAT','POWERBOAT',
    'BULLDOZER','EXCAVATOR','AMBULANCE','RECTANGLE','CATHEDRAL','MONASTERY',
    'SANCTUARY','TERRITORY','DIRECTORY','DORMITORY','INVENTORY','PLANETARY',
    'PENINSULA','LANDSCAPE',
    // everyday adjectives & abstract nouns
    'ADVERSARY','ITINERARY','LEGENDARY','NECESSARY','SECONDARY','SECRETARY',
    'TEMPORARY','VOLUNTARY','VISIONARY','INFIRMARY','DROMEDARY','CENTENARY',
    'EXEMPLARY','MERCENARY','MOMENTARY','CUSTOMARY','DIGNITARY','PULMONARY',
    'TRIBUTARY','JUDICIARY','MACHINERY','TREACHERY','CURIOSITY','AWARENESS',
    'READINESS','FRESHNESS','ROUGHNESS','TIGHTNESS','SWEETNESS','QUICKNESS',
    'THICKNESS','GREATNESS','DIZZINESS','HEAVINESS','SILLINESS','DELICIOUS',
    'RELIGIOUS','NOTORIOUS','MARVELOUS','GLAMOROUS','MURDEROUS','POISONOUS',
    'MONSTROUS','MOMENTOUS','RAPTUROUS','VICARIOUS','CONSCIOUS','ANONYMOUS',
    'HILARIOUS','HAZARDOUS','LABORIOUS','LUXURIOUS','MALICIOUS','FEROCIOUS',
    'ATROCIOUS','AUDACIOUS','BARBAROUS','CAVERNOUS','CREDULOUS','ERRONEOUS',
    'FELONIOUS','FRIVOLOUS','IMPERIOUS','INGENIOUS','INJURIOUS','JUDICIOUS',
    'LUDICROUS','NEFARIOUS','OBLIVIOUS','OBNOXIOUS','OFFICIOUS','PONDEROUS',
    'STRENUOUS','TENACIOUS','UNANIMOUS','VORACIOUS','COURTEOUS','DEXTEROUS',
    'IMPETUOUS','EFFECTIVE','DEFECTIVE','DETECTIVE','DIRECTIVE','OBJECTIVE',
    'SELECTIVE','SENSITIVE','ATTENTIVE','ASSERTIVE','EXCESSIVE','EXPENSIVE',
    'EXCLUSIVE','EXTENSIVE','EXECUTIVE','INVENTIVE','PRIMITIVE','OPERATIVE',
    'ADJECTIVE','ADDICTIVE','COGNITIVE','CORROSIVE','DEDUCTIVE','DEFENSIVE',
    'DIGESTIVE','EXPLOSIVE','FORMATIVE','IMPULSIVE','INCLUSIVE','INDUCTIVE',
    'INFECTIVE','INTENSIVE','INTUITIVE','NORMATIVE','NUTRITIVE','OFFENSIVE',
    'PERVASIVE','PROACTIVE','RECEPTIVE','RECESSIVE','REPULSIVE','SECRETIVE',
    'SEDUCTIVE','TALKATIVE','TENTATIVE','AGREEABLE','ADMIRABLE','AVAILABLE',
    'BREAKABLE','DESIRABLE','ENJOYABLE','VENGEANCE','OBEDIENCE','MEMORABLE',
    'MISERABLE','MOUNTABLE','PEACEABLE','REMOVABLE','ADAPTABLE','ADVISABLE',
    'ALLOWABLE','ALTERABLE','AVOIDABLE','COUNTABLE','DEBATABLE','DEFINABLE',
    'DRINKABLE','ENDURABLE','EQUITABLE','EXCITABLE','EXCUSABLE','FLAMMABLE',
    'HABITABLE','IMMOVABLE','IMMUTABLE','INCAPABLE','INCURABLE','IRRITABLE',
    'LAUGHABLE','LEARNABLE','MALLEABLE','NAVIGABLE','OPPOSABLE','PALATABLE',
    'PERMEABLE','PRINTABLE','REACHABLE','RELATABLE','SEPARABLE','SHAREABLE',
    'SPEAKABLE','STOPPABLE','SWIMMABLE','TEACHABLE','THINKABLE','TOLERABLE',
    'TOUCHABLE','TRACEABLE','TRAINABLE','TREATABLE','UNLIKABLE','UNLOVABLE',
    'VENERABLE','VERITABLE','DIVISIBLE','ILLEGIBLE','INAUDIBLE','INDELIBLE',
    'INVISIBLE','PLAUSIBLE','REDUCIBLE','CLASSICAL','POLITICAL','PRACTICAL',
    'TECHNICAL','IDENTICAL','NUMERICAL','SATIRICAL','WHIMSICAL','SPHERICAL',
    'BOTANICAL','SCEPTICAL','ILLOGICAL','SOMETHING','PLAYTHING','GARDENING',
    'LISTENING','SCREAMING','WANDERING','WHISTLING','SHIVERING','TREMBLING',
    'STUMBLING','GRUMBLING','CHUCKLING','SPARKLING','TWINKLING','SPLASHING',
    'CRACKLING','SOFTENING','DARKENING','WEAKENING','DEEPENING','WORSENING',
    'LOOSENING','UNDERLING','EARTHLING','BEGINNING','ADORATION','AFFECTION',
    'ATTENTION','CONDITION','DEDUCTION','DEFECTION','DEFLATION','DECEPTION',
    'DETECTION','DEVIATION','ELEVATION','EMULATION','EVOLUTION','EXCEPTION',
    'EXECUTION','EXEMPTION','EXTORTION','FORMATION','GRADATION','GESTATION',
    'IMITATION','INCEPTION','INDUCTION','INFECTION','INFLATION','INJECTION',
    'INSERTION','INTENTION','ISOLATION','ITERATION','MIGRATION','NARRATION',
    'OPERATION','PARTITION','PREDATION','PROBATION','PROMOTION','QUOTATION',
    'RADIATION','REDUCTION','REJECTION','RETENTION','SECRETION','SEDUCTION',
    'SELECTION','SENSATION','SITUATION','TRADITION','VALUATION','VARIATION',
    'VIBRATION','VIOLATION','AGREEMENT','ALIGNMENT','AMENDMENT','AMUSEMENT',
    'APARTMENT','ATONEMENT','ENACTMENT','ENDOWMENT','ENJOYMENT','EQUIPMENT',
    'FIRMAMENT','IMPLEMENT','INCREMENT','JUDGEMENT','MERRIMENT','PARCHMENT',
    'PLACEMENT','SACRAMENT','SENTIMENT','STATEMENT','TESTAMENT','TREATMENT',
    'REPAYMENT','DETRIMENT'
  ];

  // A separate pool of genuine plural 9-letter words — pickBonusWord()
  // below draws from here only ~1 game in 10 on average, so Round 5 is
  // mostly singular/base-form words with the occasional plural, rather than
  // never having one at all. Same two-way verification as BONUS_WORDS
  // above (in data/dictionary.txt, not in geo-data.js).
  const BONUS_WORDS_PLURAL = [
    'ELEPHANTS','COMPUTERS','DINOSAURS','MOUNTAINS','CHEMICALS','BUILDINGS',
    'BATTERIES','VERTEBRAE','RAINCOATS','ALPHABETS','ASTEROIDS','BACKPACKS',
    'BIRTHDAYS','CALENDARS','CONTRACTS','CUSTOMERS','DEADLINES','EMPLOYEES',
    'HOSPITALS','KANGAROOS','KEYBOARDS','NOTEBOOKS','PAINTINGS','PASSWORDS',
    'QUESTIONS','SCHEDULES','SENTENCES','TRIANGLES','UMBRELLAS','UNIVERSES',
    'VACATIONS'
  ];
  const PLURAL_CHANCE = 0.1;

  // The one function Round 5 should ever call for its target word — keeps
  // the "mostly singular, rarely plural, never a place name" rule in this
  // one place rather than duplicated at the call site.
  function pickBonusWord() {
    const pool = Math.random() < PLURAL_CHANCE ? BONUS_WORDS_PLURAL : BONUS_WORDS;
    return pool[Math.floor(Math.random() * pool.length)];
  }

  // Relative weights (not percentages — just proportional) modelling real
  // English letter frequency, so V/C presses tend to produce a playable
  // rack instead of a uniformly-random one. The player still fully
  // controls the vowel/consonant ratio via which button they press.
  const VOWEL_WEIGHTS = { A: 9, E: 12, I: 9, O: 8, U: 3 };
  const CONSONANT_WEIGHTS = {
    T: 9, N: 8, R: 8, S: 8, L: 5, D: 5, C: 4, M: 4, P: 4, H: 4,
    B: 2, F: 2, G: 3, W: 2, Y: 2, V: 1, K: 1, J: 1, X: 1, Q: 1, Z: 1
  };

  function weightedPick(table) {
    const entries = Object.entries(table);
    const total = entries.reduce((sum, [, w]) => sum + w, 0);
    let r = Math.random() * total;
    for (const [letter, w] of entries) {
      r -= w;
      if (r <= 0) return letter;
    }
    return entries[entries.length - 1][0];
  }

  window.QZAnagramData = {
    BONUS_WORDS,
    BONUS_WORDS_PLURAL,
    pickBonusWord,
    randomVowel: () => weightedPick(VOWEL_WEIGHTS),
    randomConsonant: () => weightedPick(CONSONANT_WEIGHTS)
  };
})();
